In [1]:

import numpy as np
import pandas as pd
import os
import csv
import cv2
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score

In [4]:
data1 = pd.read_csv(r"D:\thirdyr_sem2\iotproj\dataset\EMG_FEA_out_Tst.csv")
data2 = pd.read_csv(r"D:\thirdyr_sem2\iotproj\dataset\EMG_FEA_out_TRN.csv")
data = data1.append(data2)

C:\Users\sahil\AppData\Local\Temp\ipykernel_1288\3794909076.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data1.append(data2)


In [5]:
data

1.924862952378711498e+03  4.387338003458980040e+01  \
0                   890.601295                 29.846431   
1                  1781.110538                 42.206907   
2                  1723.121205                 41.511423   
3                  1387.720280                 37.253987   
4                  1053.454115                 32.458021   
...                        ...                       ...   
1218                       NaN                       NaN   
1219                       NaN                       NaN   
1220                       NaN                       NaN   
1221                       NaN                       NaN   
1222                       NaN                       NaN   

      1.293264151190241137e+04  2.586528302380482103e+01  \
0                 11180.223017                 22.360446   
1                 16033.484482                 32.066969   
2                 15042.851595                 30.085703   
3                 14596.097275                 29.192195   
4                 12353.573071                 24.707146   
...                        ...                       ...   
1218                       NaN                       NaN   
1219                       NaN                       NaN   
1220                       NaN                       NaN   
1221                       NaN                       NaN   
1222                       NaN                       NaN   

      2.394962112307593088e+03  4.789924224615186077e+00  \
0                  1993.525947                  3.987052   
1                  2843.445176                  5.686890   
2                  2879.683907                  5.759368   
3                  2563.282938                  5.126566   
4                  2184.592005                  4.369184   
...                        ...                       ...   
1218                       NaN                       NaN   
1219                       NaN                       NaN   
1220                       NaN                       NaN   
1221                       NaN                       NaN   
1222                       NaN                       NaN   

      0.000000000000000000e+00  4.000000000000000000e+00  \
0                          0.0                       6.0   
1                          0.0                       6.0   
2                          0.0                       5.0   
3                          0.0                      10.0   
4                          0.0                       5.0   
...                        ...                       ...   
1218                       0.0                       NaN   
1219                       0.0                       NaN   
1220                       0.0                       NaN   
1221                       0.0                       NaN   
1222                       0.0                       NaN   

      4.000000000000000000e+01  2.479999999999999982e-01  ...  \
0                         48.0                     0.328  ...   
1                         46.0                     0.352  ...   
2                         46.0                     0.316  ...   
3                         69.0                     0.354  ...   
4                         49.0                     0.374  ...   
...                        ...                       ...  ...   
1218                       NaN                       NaN  ...   
1219                       NaN                       NaN  ...   
1220                       NaN                       NaN  ...   
1221                       NaN                       NaN  ...   
1222                       NaN                       NaN  ...   

      2.856052381302370335e+01  2.284166095874597959e+05  \
0                          NaN                       NaN   
1                          NaN                       NaN   
2                          NaN                       NaN   
3                          NaN                       NaN   
4                          NaN           

In [11]:
distortions = []
K = range(1,10)
for k in K:
    kmeanModel = KMeans(n_clusters=k)
    kmeanModel.fit(data)
    distortions.append(kmeanModel.inertia_)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(16,8))
plt.plot(K, distortions, 'bx-')
plt.xlabel('k')
plt.ylabel('Distortion')
plt.title('The Elbow Method showing the optimal k')
plt.show()

In [ ]:
kmeans = KMeans(n_clusters=16)
kmeans.fit(data)

In [6]:
x=[]
xt=[]
y=[]
yt=[]

In [7]:
x = data.iloc[:,0:-1-1].values
xt =  data.iloc[:,0:-1-1].values

y = data.iloc[:,-1].values
yt= data.iloc[:,-1].values


In [8]:
x_train = x
y_train = y
x_test = xt
y_test = yt

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

In [9]:
#Decision Tree Classifier
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

#from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
acc=[]
depth=[]
for mdepth in range(2, 20, 1):
    
    
    model1 = DecisionTreeClassifier(criterion = "gini",  #gini entropy
            random_state = 17000,max_depth=mdepth, min_samples_leaf=5)

    model1.fit(x_train, y_train)
    
    #predicting the traget variable using testing variables
    y_pred1 = model1.predict(x_test)
    #Results
    #print("Decision Tree Results")
    #print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")
    acc.append(accuracy_score(y_test, y_pred1))
    depth.append(mdepth)
#printing results of loop
#print(acc)
#print(depth)
max_acc_index = acc.index(max(acc))  
#print (max_acc_index)
print ('Optimum Depth is = ', depth[max_acc_index])
acc_max =   acc[max_acc_index]
print('Training ACC=', acc_max*100,'%')
optimum_depth = depth[max_acc_index]

#Using optimum depth value to train the model 
optimum_model = DecisionTreeClassifier(max_depth = optimum_depth) 
optimum_model.fit(x_train, y_train)

#Test the model 
y_pred = optimum_model.predict(x_test)




orig_class = y_test
pred_class = y_pred

print('ACC = ',accuracy_score(orig_class, pred_class))
print('RECALL = ', recall_score(orig_class, pred_class))
print('PRECISION = ', precision_score(orig_class, pred_class))
print('F1 SCORE = ', f1_score(orig_class, pred_class))

y_pred=[]

Optimum Depth is =  6
Training ACC= 67.75510204081633 %
ACC =  0.6816326530612244
RECALL =  0.7033898305084746
PRECISION =  0.6587301587301587
F1 SCORE =  0.680327868852459


In [10]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
import seaborn as sns
from pandas.plotting import register_matplotlib_converters

# Train a single random forest classifier
clf = RandomForestClassifier(max_depth=2, random_state=0, n_estimators = 100)
clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)

# Create a confusion matrix
cnf_matrix = confusion_matrix(y_test, y_pred)


orig_class = y_test
pred_class = y_pred

print('ACC = ',accuracy_score(orig_class, pred_class))
print('RECALL = ', recall_score(orig_class, pred_class))
print('PRECISION = ', precision_score(orig_class, pred_class))
print('F1 SCORE = ', f1_score(orig_class, pred_class))

y_pred =[]

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [11]:
#Random forest classiffier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
model2 = RandomForestClassifier(n_estimators = 100)
model2.fit(x_train, y_train)
y_pred2 = model2.predict(x_test)
print("Random Forest Clasifier")
print("Random Forest Accuracy: ",accuracy_score(y_test, y_pred2)*100,"%")
print("Train Accuracy:",model2.score(x_train, y_train))
print("Test Accuracy:",model2.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred2, average='weighted'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred2, average='weighted'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred2, average='weighted'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred2))

Random Forest Clasifier
Random Forest Accuracy:  75.91836734693878 %
Train Accuracy: 1.0
Test Accuracy: 0.7591836734693878
Precision Score:  0.7591286193964766
Recall Score:  0.7591836734693878
F1 Score:  0.759143487182107
Confusion Matrix: 
[[98 29]
 [30 88]]


In [12]:
#LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression
model3 = LogisticRegression(multi_class='multinomial', solver='lbfgs')
model3.fit(x_train, y_train)
y_pred3 = model3.predict(x_test)
CM = confusion_matrix(y_test, y_pred3)
print("LogisticRegression Results")
print("Train Accuracy:",model3.score(x_train, y_train))
print("Test Accuracy:",model3.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred3, average="micro"))
print("Recall Score: ",metrics.recall_score(y_test, y_pred3,average="micro")) # true positive rate, Sensitivity
print("F2 Score: ",metrics.fbeta_score(y_test, y_pred3, beta=2.0,average="micro"))
print("F1 Score: ",metrics.f1_score(y_test, y_pred3,average="micro"))
print("Confusion Matrix: ")

LogisticRegression Results
Train Accuracy: 0.5470347648261759
Test Accuracy: 0.5591836734693878
Precision Score:  0.5591836734693878
Recall Score:  0.5591836734693878
F2 Score:  0.5591836734693878
F1 Score:  0.5591836734693878
Confusion Matrix: 


C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
#SUPPORT VECTOR MACHINE-POLY KERNEL
from sklearn import svm
model4 = svm.SVC(kernel='poly', degree=3, probability=True)
model4.fit(x_train, y_train)
y_pred4 = model4.predict(x_test)
CM = confusion_matrix(y_test, y_pred4)
print("SVM Polynomial")
print("Train Accuracy:",model4.score(x_train, y_train))
print("Test Accuracy:",model4.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred4, average="micro"))
print("Recall Score: ",metrics.recall_score(y_test, y_pred4,average="micro")) # true positive rate, Sensitivity
print("F2 Score: ",metrics.fbeta_score(y_test, y_pred4, beta=2.0,average="micro"))
print("F1 Score: ",metrics.f1_score(y_test, y_pred4,average="micro"))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred4))

SVM Polynomial
Train Accuracy: 0.5132924335378323
Test Accuracy: 0.5183673469387755
Precision Score:  0.5183673469387755
Recall Score:  0.5183673469387755
F2 Score:  0.5183673469387755
F1 Score:  0.5183673469387755
Confusion Matrix: 
[[127   0]
 [118   0]]


In [16]:
from sklearn import svm
model5 = svm.SVC(kernel='sigmoid', probability=True)
model5.fit(x_train, y_train)
y_pred5 = model5.predict(x_test)
CM = confusion_matrix(y_test, y_pred5)
print("SVM Polynomial")
print("Train Accuracy:",model5.score(x_train, y_train))
print("Test Accuracy:",model5.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred5, average="micro"))
print("Recall Score: ",metrics.recall_score(y_test, y_pred5,average="micro")) # true positive rate, Sensitivity
print("F2 Score: ",metrics.fbeta_score(y_test, y_pred5, beta=2.0,average="micro"))
print("F1 Score: ",metrics.f1_score(y_test, y_pred5,average="micro"))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred5))

SVM Polynomial
Train Accuracy: 0.5122699386503068
Test Accuracy: 0.5183673469387755
Precision Score:  0.5183673469387755
Recall Score:  0.5183673469387755
F2 Score:  0.5183673469387755
F1 Score:  0.5183673469387755
Confusion Matrix: 
[[127   0]
 [118   0]]


In [17]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import confusion_matrix
model6 = KNeighborsClassifier(n_neighbors = 5)
model6.fit(x_train, y_train)
y_pred6 = model6.predict(x_test)
print("KNN")
print("KnnAccuracy: ",accuracy_score(y_test, y_pred6)*100,"%")
print("Train Accuracy:",model6.score(x_train, y_train))
print("Test Accuracy:",model6.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred6, average='weighted'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred6, average='weighted'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred6, average='weighted'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred6))


KNN
KnnAccuracy:  56.734693877551024 %
Train Accuracy: 0.6983640081799591
Test Accuracy: 0.5673469387755102
Precision Score:  0.5673469387755102
Recall Score:  0.5673469387755102
F1 Score:  0.5673469387755102
Confusion Matrix: 
[[74 53]
 [53 65]]
